version: "3"

services:
  app:
    build: .
    image: card-deck-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: .env

  golang:
    image: golang:1.18-alpine
    volumes:
      - .:/code:cached
    working_dir: /code
    env_file: .env
    environment:
      - GOPATH=/code/.go
      - CGO_ENABLED=0

  mockery:
    image: vektra/mockery
    volumes:
      - .:/code:cached
    working_dir: /code

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d/:delegated
    environment:
      - POSTGRES_DB=card_deck_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
