// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpError is an autogenerated mock type for the HttpError type
type HttpError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *HttpError) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StatusCode provides a mock function with given fields:
func (_m *HttpError) StatusCode() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type NewHttpErrorT interface {
	mock.TestingT
	Cleanup(func())
}

// NewHttpError creates a new instance of HttpError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHttpError(t NewHttpErrorT) *HttpError {
	mock := &HttpError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
